plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.170'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = 'https://maven.neoforged.net/releases' }
    maven { url = 'https://maven.blamejared.com' }
    maven {
        url = 'https://maven.latvian.dev/releases'
        content {
            includeGroup 'dev.latvian.mods'
            includeGroup 'dev.latvian.apps'
        }
    }
    maven {
        url = 'https://maven.latvian.dev/mirror'
        content {
            includeGroup 'dev.architectury'
            includeGroup 'me.shedaniel'
            includeGroup 'me.shedaniel.cloth'
            includeGroup 'mezz.jei'
            includeGroup 'net.darkhax.bookshelf'
            includeGroup 'net.darkhax.gamestages'
            includeGroup 'dev.emi'
            includeGroup 'com.github.rtyley'
        }
    }
}

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        argument '--nogui'
    }

    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        arguments.addAll '--mod', project.mod_id, '--all',
                '--output', file('src/generated/resources/').absolutePath,
                '--existing', file('src/main/resources/').absolutePath
    }
}

sourceSets {
    main {
        java {
            setSrcDirs(['src/port/java'])
        }
        resources {
            setSrcDirs(['src/main/resources', 'src/generated/resources'])
            exclude 'mcmod.info'
            exclude 'mixins.mmce_*.json'
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
    compileOnly "com.blamejared.crafttweaker:CraftTweaker-neoforge-1.21.1:21.0.38"
    compileOnly "dev.latvian.mods:kubejs-neoforge:2101.7.2-build.369"
    compileOnly "dev.latvian.mods:rhino:2101.2.7-build.81"
}

tasks.withType(ProcessResources).configureEach {
    def replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }

    from('src/main/resources/assets/modularmachinery/default_machinery') {
        into 'data/modularmachinery/mmce_machinery'
        include '**/*.json'
    }
    from('src/main/resources/assets/modularmachinery/default_recipes') {
        into 'data/modularmachinery/mmce_recipes'
        include '**/*.json'
    }
    from('src/main/resources/assets/modularmachinery/default_variables') {
        into 'data/modularmachinery/mmce_variables'
        include '**/*.json'
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
