org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=false
org.gradle.configuration-cache=false
org.gradle.java.installations.auto-download=true
org.gradle.java.home=C:/Program Files/Java/jdk-21
org.gradle.java.installations.paths=C:/Program Files/Java/jdk-21

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.219
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=modularmachinery
mod_name=Modular Machinery: Community Edition
mod_license=GPL-3.0-only
mod_version=2.3.2-neoforge.0
mod_group_id=hellfirepvp.modularmachinery
mod_authors=HellFirePvP, wiiv, KasumiNova, youyihj, ikexing, NovaEngineering-Source contributors
mod_description=NeoForge 1.21.1 port of Modular Machinery: Community Edition with scriptable modular machines and recipes.
