modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/NovaEngineering-Source/ModularMachinery-Community-Edition"
logoFile="assets/modularmachinery/textures/logo.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="crafttweaker"
type="optional"
versionRange="[1.21.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="kubejs"
type="optional"
versionRange="[2101,)"
ordering="AFTER"
side="BOTH"
